# Generated by Django 4.1.4 on 2022-12-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=254)),
                ('prenom', models.CharField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=254)),
                ('nationalite', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
    ]
